# Generated by Django 5.1.6 on 2025-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsagreement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="termsagreement",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="termsagreement",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
