# Generated by Django 5.1.6 on 2025-03-05 07:14

import django.db.models.deletion
from django.db import migrations, models

import apps.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChapterVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "video_url",
                    models.FileField(blank=True, null=True, upload_to=apps.common.utils.class_lecture_file_path),
                ),
            ],
            options={
                "db_table": "chapter_video",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_duration", models.SmallIntegerField(default=0)),
                ("max_students", models.SmallIntegerField(default=0)),
            ],
            options={
                "db_table": "class",
            },
        ),
        migrations.CreateModel(
            name="LectureChapter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "material_url",
                    models.FileField(blank=True, null=True, upload_to=apps.common.utils.class_lecture_file_path),
                ),
            ],
            options={
                "db_table": "lecture_chapter",
            },
        ),
        migrations.CreateModel(
            name="ProgressTracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("progress", models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ("is_completed", models.BooleanField(default=False)),
                ("last_watched_time", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "progress_tracking",
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to=apps.common.utils.class_lecture_file_path),
                ),
                ("introduction", models.CharField(max_length=1000)),
                ("learning_objective", models.CharField(max_length=255)),
                ("progress_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
            ],
            options={
                "db_table": "lecture",
            },
        ),
    ]
