# Generated by Django 5.1.6 on 2025-03-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="instructor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="lecturechapter",
            name="lecture",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.lecture"),
        ),
        migrations.AddField(
            model_name="chaptervideo",
            name="lecture_chapter",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.lecturechapter"),
        ),
        migrations.AddField(
            model_name="progresstracking",
            name="chapter_video",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.chaptervideo"),
        ),
        migrations.AddField(
            model_name="progresstracking",
            name="student",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.student"),
        ),
        migrations.AlterUniqueTogether(
            name="progresstracking",
            unique_together={("student", "chapter_video")},
        ),
    ]
