# Generated by Django 5.1.6 on 2025-03-12 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0002_alter_user_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="instructor",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="users.instructor"),
        ),
    ]
