# Generated by Django 5.1.6 on 2025-03-10 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0002_initial"),
        ("users", "0002_alter_user_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.student"),
        ),
    ]
