# Generated by Django 5.1.6 on 2025-03-05 07:14

from django.db import migrations, models

import apps.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=1000)),
                (
                    "file_url",
                    models.FileField(blank=True, null=True, upload_to=apps.common.utils.assignment_material_path),
                ),
            ],
            options={
                "db_table": "assignment",
            },
        ),
        migrations.CreateModel(
            name="AssignmentComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_url",
                    models.FileField(blank=True, null=True, upload_to=apps.common.utils.assignment_comment_file_path),
                ),
                ("content", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "assignment_comment",
            },
        ),
    ]
