# Generated by Django 5.1.6 on 2025-03-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="chapter_video",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.chaptervideo"),
        ),
        migrations.AddField(
            model_name="assignmentcomment",
            name="assignment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assignments.assignment"),
        ),
        migrations.AddField(
            model_name="assignmentcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="assignments.assignmentcomment",
            ),
        ),
    ]
