# Generated by Django 5.1.6 on 2025-03-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_nickname", models.CharField(max_length=20)),
                ("star", models.DecimalField(decimal_places=1, max_digits=2)),
                ("content", models.CharField(max_length=200)),
                ("lecture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.lecture")),
            ],
            options={
                "db_table": "review",
            },
        ),
    ]
