name: Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose -v

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_NAME }}/oz_joint_dev:latest .
          docker build -t ${{ secrets.DOCKERHUB_NAME }}/oz_joint_nginx:latest ./resources/nginx
          docker push ${{ secrets.DOCKERHUB_NAME }}/oz_joint_dev:latest
          docker push ${{ secrets.DOCKERHUB_NAME }}/oz_joint_nginx:latest

      - name: Deploy to Server NCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd app
            docker pull ${{ secrets.DOCKERHUB_NAME }}/oz_joint_dev:latest
            docker pull ${{ secrets.DOCKERHUB_NAME }}/oz_joint_nginx:latest
            docker-compose --env-file .envs/.dev.env up -d -build
            docker ps